### PR TITLE
Security fix. Fixes #37

### LINKED ISSUE #37: [BUG] Kicking Player for Exploiting
**Describe the bug**
Tow job is kicking players for doing the AI tow job for exploiting. 

**To Reproduce**
1. Get the tow job
2. Start NPC mission
3. Pull up to the vehicle to tow onto flatbed
4. Once it attaches to flatbed, server will kick you for exploiting 

**Questions (please complete the following information):**
 - When you last updated: [6/18/22]
 - Are you using custom resource? which ones? [qb-target]
 - Have you renamed `qb-` to something custom? [no]

### PR DESCRIPTION
**Pull request by tom-osborne**
**Describe Pull request**
This PR prevents the player from being kicked when towing a vehicle while still maintaining the distance check. This area of the code could definitely benefit from a full re-work, but this serves to at least make the job useable for now.

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes] (Be honest)
- Does your code fit the style guidelines? [yes]
- Does your PR fit the contribution guidelines? [yes]

### CODE REVIEW

File: client/main.lua [hunk 1]
```diff
@@ -1,5 +1,5 @@
 local QBCore = exports['qb-core']:GetCoreObject()
-local PlayerJob = {}
+local PlayerJob = QBCore.Functions.GetPlayerData().job
```
Comment (BerkieBb) [inline client/main.lua:2]: You should make this PlayerData instead of trying to grab the job of a possible nil value which could end the execution of the resource once it errors out, then change PlayerJob to PlayerData.job

File: server/main.lua [hunk 2]
```diff
@@ -34,11 +34,12 @@ RegisterNetEvent('qb-tow:server:nano', function(targetVehicle)
...
 
     local playerPed = GetPlayerPed(src)
-    local playerVehicle = GetVehiclePedIsIn(playerPed, false)
+    local playerVehicle = GetVehiclePedIsIn(playerPed, true)
     local playerVehicleCoords = GetEntityCoords(playerVehicle)
     local targetVehicleCoords = GetEntityCoords(targetVehicle)
     if Player.PlayerData.job.name ~= "tow" or #(playerVehicleCoords - targetVehicleCoords) > 11.0 then
-        return DropPlayer(src, "Attempted exploit abuse")
+        -- return DropPlayer(src, "Attempted exploit abuse")
+        print("KICKED")
```
Comment (BerkieBb) [inline server/main.lua:42]: A print?

**Review by BerkieBb — CHANGES_REQUESTED** [review]

File: server/main.lua (hunk 2 above)
Comment (tom-osborne) [reply server/main.lua:42]: Ah leftover from testing

File: client/main.lua (hunk 1 above)
Comment (tom-osborne) [reply client/main.lua]: Done.

File: server/main.lua (hunk 2 above)
Comment (tom-osborne) [reply server/main.lua]: Uncommented drop player line and removed comment

**Review by BerkieBb — APPROVED** [review]
